/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Consultorio.view;

import javax.swing.ImageIcon;
import Consultorio.dao.ConsultaDao;
import Consultorio.object.Consulta;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Douglas
 */
public class FrmConsultaA extends javax.swing.JFrame {
    public void listar(){
        ConsultaDao dao = new ConsultaDao();
        List<Consulta> lista = dao.listarConsulta();
        DefaultTableModel dados = (DefaultTableModel) tbconsultaa.getModel();
        dados.setNumRows(0);
        
        for (Consulta c : lista){
            dados.addRow(new Object[]{
                c.getId(),    
                c.getPaciente(),
                c.getNomep(),
                c.getObs(),
                c.getProfissionalsaude(),
                c.getValor(),
                c.getDataconsulta(),
                c.getTurnoconsulta()
            });
        }
    }

    /**
     * Creates new form FrmConsultaA
     */
    public FrmConsultaA() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbconsultaa = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consultas Agendadas");
        setIconImage(new ImageIcon(getClass().getResource("/Consultorio/imagem/11-removebg-preview.png")).getImage()
        );
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        tbconsultaa.setBorder(new javax.swing.border.MatteBorder(null));
        tbconsultaa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código Consulta", "CPF", "Nome", "Obs", "Especialista", "Valor", "Data da Consulta", "Turno da Consulta"
            }
        ));
        tbconsultaa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbconsultaaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbconsultaa);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

        listar();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void tbconsultaaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbconsultaaMouseClicked
/*
        
        
        tfcpf.setText(tbconsultaa.getValueAt(tbconsultaa.getSelectedRow(), 0).toString());
        tfnome.setText(tbconsultaa.getValueAt(tbconsultaa.getSelectedRow(), 1).toString());
        tfobs.setText(tbconsultaa.getValueAt(tbconsultaa.getSelectedRow(), 2).toString());
        cbespecialista.setText(tbconsultaa.getValueAt(tbconsultaa.getSelectedRow(), 3).toString());
        tfdata.setText(tbconsultaa.getValueAt(tbconsultaa.getSelectedRow(), 5).toString());
        cbturno.setText(tbconsultaa.getValueAt(tbconsultaa.getSelectedRow(), 6).toString());
        
        */// TODO add your handling code here:
    }//GEN-LAST:event_tbconsultaaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmConsultaA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmConsultaA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmConsultaA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmConsultaA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmConsultaA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbconsultaa;
    // End of variables declaration//GEN-END:variables
}
